[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
pythonpath = .
markers =
    unit: 标记单元测试
    api: 标记API测试
    integration: 标记集成测试
    e2e: 标记端到端测试